spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.56.101:3306/chen
    password: 123456
    username: root
  jpa:
    show-sql: true
  rabbitmq:
    addresses: 192.168.56.101
    port: 5672
  redis:
    host: 192.168.56.101
    port: 6379
    
evi:
  chen
